name: healthcare_app
description: "SIH 2026 - Rural Healthcare Access App for Maharashtra"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.13.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State management
  provider: ^6.1.2

  # Navigation
  go_router: ^14.6.2

  # Local persistence
  shared_preferences: ^2.3.3

  # Fonts (Noto Sans for Devanagari support)
  google_fonts: ^6.2.1

  # Icons
  cupertino_icons: ^1.0.8

  # Internationalization
  intl: ^0.20.1
  firebase_core: ^4.15.0
  firebase_auth: ^6.7.0
  cloud_firestore: ^6.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  generate: true
  uses-material-design: true
